# Generated by Django 3.1 on 2021-01-02 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20201120_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='videosview',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videos.video')),
            ],
            bases=(django.views.generic.list.ListView, 'videos.video'),
        ),
    ]
